"""Add helper fields to user model

Revision ID: 54ed49768a8a
Revises: c6a358d8f0ac
Create Date: 2026-01-05 11:44:23.071359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ed49768a8a'
down_revision = 'c6a358d8f0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_helper', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('helper_categories', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('helper_categories')
        batch_op.drop_column('skills')
        batch_op.drop_column('is_helper')

    # ### end Alembic commands ###
