"""Add TOTP 2FA fields

Revision ID: 718f1abd1e2f
Revises: 54ed49768a8a
Create Date: 2026-01-07 09:10:24.878678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718f1abd1e2f'
down_revision = '54ed49768a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', name='unique_user_favorite')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('totp_backup_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_backup_codes')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    op.drop_table('favorites')
    # ### end Alembic commands ###
