"""add translation cache table

Revision ID: 959f3683a5c3
Revises: 199fa9f6522b
Create Date: 2026-01-10 11:26:34.704840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959f3683a5c3'
down_revision = '199fa9f6522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('source_lang', sa.String(length=5), nullable=False),
    sa.Column('target_lang', sa.String(length=5), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_hash', 'target_lang', name='unique_translation')
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_cache_text_hash'), ['text_hash'], unique=False)

    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offerings_is_boosted'), ['is_boosted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offerings_is_boosted'))

    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_text_hash'))

    op.drop_table('translation_cache')
    # ### end Alembic commands ###
